// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PrepaidEngine.Infrastructure.Persistence;

#nullable disable

namespace PrepaidEngine.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(PrepaidEngineDbContext))]
    [Migration("20260909183702_AddTmcAndCpmcToPrepaidBill")]
    partial class AddTmcAndCpmcToPrepaidBill
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PrepaidEngine.Domain.Entities.Consumer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AccountNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<decimal>("ConnectedLoadKw")
                        .HasColumnType("decimal(18,3)");

                    b.Property<string>("ConnectionStatus")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<Guid>("MeterId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("ServiceAddress")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("AccountNumber")
                        .IsUnique();

                    b.HasIndex("MeterId")
                        .IsUnique();

                    b.ToTable("Consumers", (string)null);
                });

            modelBuilder.Entity("PrepaidEngine.Domain.Entities.ConsumptionReading", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ConsumerId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("ConsumptionKwh")
                        .HasColumnType("decimal(18,3)");

                    b.Property<DateTime>("PeriodEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("PeriodStart")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ConsumerId");

                    b.ToTable("ConsumptionReadings", (string)null);
                });

            modelBuilder.Entity("PrepaidEngine.Domain.Entities.FppasCharge", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("NotifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("RateFraction")
                        .HasColumnType("decimal(9,4)");

                    b.Property<decimal>("SourceEnergyCharge")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("FppasCharges", (string)null);
                });

            modelBuilder.Entity("PrepaidEngine.Domain.Entities.PrepaidBill", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("AmountPaid")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("ConsumerId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ConsumptionReadingId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("CpmcAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ElectricityDutyAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("EnergyChargeGross")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("FixedCharge")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("FppasAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid?>("FppasChargeId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("GeneratedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("PrepaidRebateAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<Guid>("TariffId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("TmcAmount")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ConsumerId");

                    b.HasIndex("ConsumptionReadingId")
                        .IsUnique();

                    b.HasIndex("FppasChargeId");

                    b.HasIndex("TariffId");

                    b.ToTable("PrepaidBills", (string)null);
                });

            modelBuilder.Entity("PrepaidEngine.Domain.Entities.PrepaidWallet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Balance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("ConsumerId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("EmergencyCreditLimit")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ConsumerId")
                        .IsUnique();

                    b.ToTable("PrepaidWallets", (string)null);
                });

            modelBuilder.Entity("PrepaidEngine.Domain.Entities.RechargeTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ConsumerId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("InitiatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RmsReferenceId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("Id");

                    b.HasIndex("ConsumerId");

                    b.HasIndex("RmsReferenceId")
                        .IsUnique();

                    b.ToTable("RechargeTransactions", (string)null);
                });

            modelBuilder.Entity("PrepaidEngine.Domain.Entities.SmartMeter", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("LastReadingAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("LastReadingKwh")
                        .HasColumnType("decimal(18,3)");

                    b.Property<string>("MeterNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Phase")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("MeterNumber")
                        .IsUnique();

                    b.ToTable("Meters", (string)null);
                });

            modelBuilder.Entity("PrepaidEngine.Domain.Entities.Tariff", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<decimal>("EmergencyCreditLimit")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("FixedChargePerUnitPerMonth")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("MaxVendAmountSinglePhase")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("MaxVendAmountThreePhase")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("MinVendAmountSinglePhase")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("MinVendAmountThreePhase")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal>("PrepaidEnergyRebatePercent")
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Tariffs", (string)null);
                });

            modelBuilder.Entity("PrepaidEngine.Domain.Entities.WalletTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Reference")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<Guid>("WalletId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("WalletId");

                    b.ToTable("WalletTransactions", (string)null);
                });

            modelBuilder.Entity("PrepaidEngine.Domain.Entities.Consumer", b =>
                {
                    b.HasOne("PrepaidEngine.Domain.Entities.SmartMeter", "Meter")
                        .WithOne()
                        .HasForeignKey("PrepaidEngine.Domain.Entities.Consumer", "MeterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Meter");
                });

            modelBuilder.Entity("PrepaidEngine.Domain.Entities.ConsumptionReading", b =>
                {
                    b.HasOne("PrepaidEngine.Domain.Entities.Consumer", null)
                        .WithMany()
                        .HasForeignKey("ConsumerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("PrepaidEngine.Domain.Entities.PrepaidBill", b =>
                {
                    b.HasOne("PrepaidEngine.Domain.Entities.Consumer", null)
                        .WithMany()
                        .HasForeignKey("ConsumerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PrepaidEngine.Domain.Entities.ConsumptionReading", null)
                        .WithMany()
                        .HasForeignKey("ConsumptionReadingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PrepaidEngine.Domain.Entities.FppasCharge", null)
                        .WithMany()
                        .HasForeignKey("FppasChargeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PrepaidEngine.Domain.Entities.Tariff", null)
                        .WithMany()
                        .HasForeignKey("TariffId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("PrepaidEngine.Domain.Entities.PrepaidWallet", b =>
                {
                    b.HasOne("PrepaidEngine.Domain.Entities.Consumer", null)
                        .WithOne("Wallet")
                        .HasForeignKey("PrepaidEngine.Domain.Entities.PrepaidWallet", "ConsumerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PrepaidEngine.Domain.Entities.RechargeTransaction", b =>
                {
                    b.HasOne("PrepaidEngine.Domain.Entities.Consumer", null)
                        .WithMany()
                        .HasForeignKey("ConsumerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("PrepaidEngine.Domain.Entities.Tariff", b =>
                {
                    b.OwnsMany("PrepaidEngine.Domain.Entities.TariffSlab", "Slabs", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid");

                            b1.Property<decimal>("FromKwh")
                                .HasColumnType("decimal(18,3)");

                            b1.Property<decimal>("RatePerKwh")
                                .HasColumnType("decimal(18,4)");

                            b1.Property<Guid>("TariffId")
                                .HasColumnType("uuid");

                            b1.Property<decimal?>("UpToKwh")
                                .HasColumnType("decimal(18,3)");

                            b1.HasKey("Id");

                            b1.HasIndex("TariffId");

                            b1.ToTable("TariffSlabs", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("TariffId");
                        });

                    b.Navigation("Slabs");
                });

            modelBuilder.Entity("PrepaidEngine.Domain.Entities.WalletTransaction", b =>
                {
                    b.HasOne("PrepaidEngine.Domain.Entities.PrepaidWallet", null)
                        .WithMany("Transactions")
                        .HasForeignKey("WalletId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PrepaidEngine.Domain.Entities.Consumer", b =>
                {
                    b.Navigation("Wallet")
                        .IsRequired();
                });

            modelBuilder.Entity("PrepaidEngine.Domain.Entities.PrepaidWallet", b =>
                {
                    b.Navigation("Transactions");
                });
#pragma warning restore 612, 618
        }
    }
}
