// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PrepaidEngine.Infrastructure.Persistence;

#nullable disable

namespace PrepaidEngine.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(PrepaidEngineDbContext))]
    [Migration("20260909162742_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PrepaidEngine.Domain.Entities.Consumer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AccountNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ConnectionStatus")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<Guid>("MeterId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ServiceAddress")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("AccountNumber")
                        .IsUnique();

                    b.HasIndex("MeterId")
                        .IsUnique();

                    b.ToTable("Consumers", (string)null);
                });

            modelBuilder.Entity("PrepaidEngine.Domain.Entities.ConsumptionReading", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ConsumerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("ConsumptionKwh")
                        .HasColumnType("decimal(18,3)");

                    b.Property<DateTime>("PeriodEnd")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("PeriodStart")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ConsumerId");

                    b.ToTable("ConsumptionReadings", (string)null);
                });

            modelBuilder.Entity("PrepaidEngine.Domain.Entities.PrepaidBill", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("AmountPaid")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("ConsumerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ConsumptionReadingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("GeneratedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<Guid>("TariffId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ConsumerId");

                    b.HasIndex("ConsumptionReadingId")
                        .IsUnique();

                    b.HasIndex("TariffId");

                    b.ToTable("PrepaidBills", (string)null);
                });

            modelBuilder.Entity("PrepaidEngine.Domain.Entities.PrepaidWallet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Balance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("ConsumerId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ConsumerId")
                        .IsUnique();

                    b.ToTable("PrepaidWallets", (string)null);
                });

            modelBuilder.Entity("PrepaidEngine.Domain.Entities.RechargeTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("ConsumerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("InitiatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("RmsReferenceId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.HasIndex("ConsumerId");

                    b.HasIndex("RmsReferenceId")
                        .IsUnique();

                    b.ToTable("RechargeTransactions", (string)null);
                });

            modelBuilder.Entity("PrepaidEngine.Domain.Entities.SmartMeter", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("LastReadingAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("LastReadingKwh")
                        .HasColumnType("decimal(18,3)");

                    b.Property<string>("MeterNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("MeterNumber")
                        .IsUnique();

                    b.ToTable("Meters", (string)null);
                });

            modelBuilder.Entity("PrepaidEngine.Domain.Entities.Tariff", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Tariffs", (string)null);
                });

            modelBuilder.Entity("PrepaidEngine.Domain.Entities.WalletTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Reference")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<Guid>("WalletId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("WalletId");

                    b.ToTable("WalletTransactions", (string)null);
                });

            modelBuilder.Entity("PrepaidEngine.Domain.Entities.Consumer", b =>
                {
                    b.HasOne("PrepaidEngine.Domain.Entities.SmartMeter", "Meter")
                        .WithOne()
                        .HasForeignKey("PrepaidEngine.Domain.Entities.Consumer", "MeterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Meter");
                });

            modelBuilder.Entity("PrepaidEngine.Domain.Entities.ConsumptionReading", b =>
                {
                    b.HasOne("PrepaidEngine.Domain.Entities.Consumer", null)
                        .WithMany()
                        .HasForeignKey("ConsumerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("PrepaidEngine.Domain.Entities.PrepaidBill", b =>
                {
                    b.HasOne("PrepaidEngine.Domain.Entities.Consumer", null)
                        .WithMany()
                        .HasForeignKey("ConsumerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PrepaidEngine.Domain.Entities.ConsumptionReading", null)
                        .WithMany()
                        .HasForeignKey("ConsumptionReadingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PrepaidEngine.Domain.Entities.Tariff", null)
                        .WithMany()
                        .HasForeignKey("TariffId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("PrepaidEngine.Domain.Entities.PrepaidWallet", b =>
                {
                    b.HasOne("PrepaidEngine.Domain.Entities.Consumer", null)
                        .WithOne("Wallet")
                        .HasForeignKey("PrepaidEngine.Domain.Entities.PrepaidWallet", "ConsumerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PrepaidEngine.Domain.Entities.RechargeTransaction", b =>
                {
                    b.HasOne("PrepaidEngine.Domain.Entities.Consumer", null)
                        .WithMany()
                        .HasForeignKey("ConsumerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("PrepaidEngine.Domain.Entities.Tariff", b =>
                {
                    b.OwnsMany("PrepaidEngine.Domain.Entities.TariffSlab", "Slabs", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uniqueidentifier");

                            b1.Property<decimal>("FromKwh")
                                .HasColumnType("decimal(18,3)");

                            b1.Property<decimal>("RatePerKwh")
                                .HasColumnType("decimal(18,4)");

                            b1.Property<Guid>("TariffId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<decimal?>("UpToKwh")
                                .HasColumnType("decimal(18,3)");

                            b1.HasKey("Id");

                            b1.HasIndex("TariffId");

                            b1.ToTable("TariffSlabs", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("TariffId");
                        });

                    b.Navigation("Slabs");
                });

            modelBuilder.Entity("PrepaidEngine.Domain.Entities.WalletTransaction", b =>
                {
                    b.HasOne("PrepaidEngine.Domain.Entities.PrepaidWallet", null)
                        .WithMany("Transactions")
                        .HasForeignKey("WalletId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PrepaidEngine.Domain.Entities.Consumer", b =>
                {
                    b.Navigation("Wallet")
                        .IsRequired();
                });

            modelBuilder.Entity("PrepaidEngine.Domain.Entities.PrepaidWallet", b =>
                {
                    b.Navigation("Transactions");
                });
#pragma warning restore 612, 618
        }
    }
}
