// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PrepaidEngine.Infrastructure.Persistence;

#nullable disable

namespace PrepaidEngine.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(PrepaidEngineDbContext))]
    [Migration("20260919111101_AddNetworkHierarchy")]
    partial class AddNetworkHierarchy
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PrepaidEngine.Domain.Entities.AuditEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Actor")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Details")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("NewValue")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("OldValue")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.HasKey("Id");

                    b.HasIndex("EntityType");

                    b.HasIndex("OccurredAt");

                    b.ToTable("AuditEntries", (string)null);
                });

            modelBuilder.Entity("PrepaidEngine.Domain.Entities.BillingRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("BillingDate")
                        .HasColumnType("date");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ConsumerCount")
                        .HasColumnType("integer");

                    b.Property<int>("ExceptionCount")
                        .HasColumnType("integer");

                    b.Property<DateTime>("LastHeartbeatAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ResumeAfterConsumerId")
                        .HasColumnType("uuid");

                    b.Property<string>("RunType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("Id");

                    b.HasIndex("RunType", "BillingDate")
                        .IsUnique();

                    b.ToTable("BillingRuns", (string)null);
                });

            modelBuilder.Entity("PrepaidEngine.Domain.Entities.Circle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("ZoneId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("ZoneId");

                    b.ToTable("Circles", (string)null);
                });

            modelBuilder.Entity("PrepaidEngine.Domain.Entities.ConnectivityCommand", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("AcknowledgedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CommandType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("ConsumerId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("RetryCount")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("SentAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("Id");

                    b.HasIndex("ConsumerId");

                    b.ToTable("ConnectivityCommands", (string)null);
                });

            modelBuilder.Entity("PrepaidEngine.Domain.Entities.Consumer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AccountNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("BillingMode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<decimal>("ConnectedLoadKw")
                        .HasColumnType("decimal(18,3)");

                    b.Property<string>("ConnectionStatus")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<Guid?>("DtrId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsNetMeter")
                        .HasColumnType("boolean");

                    b.Property<Guid>("MeterId")
                        .HasColumnType("uuid");

                    b.Property<string>("MobileNumber")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("ServiceAddress")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid?>("TariffId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AccountNumber")
                        .IsUnique();

                    b.HasIndex("DtrId");

                    b.HasIndex("MeterId")
                        .IsUnique();

                    b.ToTable("Consumers", (string)null);
                });

            modelBuilder.Entity("PrepaidEngine.Domain.Entities.ConsumptionReading", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ConsumerId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("ConsumptionKwh")
                        .HasColumnType("decimal(18,3)");

                    b.Property<DateTime>("PeriodEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("PeriodStart")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ConsumerId");

                    b.ToTable("ConsumptionReadings", (string)null);
                });

            modelBuilder.Entity("PrepaidEngine.Domain.Entities.ConversionRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ConsumerId")
                        .HasColumnType("uuid");

                    b.Property<string>("ConsumerNumber")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("ConsumerType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateTime>("ConversionDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DecidedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DecisionNote")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<decimal>("DiaAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("FoaAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("InitialReading")
                        .HasColumnType("decimal(18,3)");

                    b.Property<DateTime>("InitialReadingDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsPermanentConsumer")
                        .HasColumnType("boolean");

                    b.Property<decimal>("LastBillFrKvah")
                        .HasColumnType("decimal(18,3)");

                    b.Property<decimal>("LastBillFrKwh")
                        .HasColumnType("decimal(18,3)");

                    b.Property<decimal>("LastBillMaxDemandKw")
                        .HasColumnType("decimal(18,3)");

                    b.Property<DateTime>("LastBillingDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("LastReadingDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MeterSerialNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("MeterStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<decimal>("OutstandingAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("ReadingAtConversion")
                        .HasColumnType("decimal(18,3)");

                    b.Property<DateTime?>("ReconnectionDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RequestType")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<DateTime>("RequestedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime?>("TemporaryDisconnectionDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TransactionId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("ConsumerId");

                    b.HasIndex("TransactionId")
                        .IsUnique();

                    b.ToTable("ConversionRequests", (string)null);
                });

            modelBuilder.Entity("PrepaidEngine.Domain.Entities.DailyLoadProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ConsumerId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("EndCumulativeKwh")
                        .HasColumnType("decimal(18,3)");

                    b.Property<DateTime>("GeneratedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsProvisional")
                        .HasColumnType("boolean");

                    b.Property<Guid>("MeterId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("ProfileDate")
                        .HasColumnType("date");

                    b.Property<DateTime>("ReceivedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SourceReference")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal>("StartCumulativeKwh")
                        .HasColumnType("decimal(18,3)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<decimal>("TotalKwh")
                        .HasColumnType("decimal(18,3)");

                    b.HasKey("Id");

                    b.HasIndex("MeterId");

                    b.HasIndex("ProfileDate");

                    b.HasIndex("ConsumerId", "MeterId", "ProfileDate")
                        .IsUnique();

                    b.ToTable("DailyLoadProfiles", (string)null);
                });

            modelBuilder.Entity("PrepaidEngine.Domain.Entities.Division", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CircleId")
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("CircleId");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Divisions", (string)null);
                });

            modelBuilder.Entity("PrepaidEngine.Domain.Entities.Dtr", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<Guid>("FeederId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("FeederId");

                    b.ToTable("Dtrs", (string)null);
                });

            modelBuilder.Entity("PrepaidEngine.Domain.Entities.EnergyValidationResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("ActualValueKwh")
                        .HasColumnType("decimal(18,3)");

                    b.Property<Guid>("ConsumerId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("EvaluatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("ExpectedValueKwh")
                        .HasColumnType("decimal(18,3)");

                    b.Property<Guid>("MeterId")
                        .HasColumnType("uuid");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Rule")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateOnly>("ValidationDate")
                        .HasColumnType("date");

                    b.Property<decimal>("VarianceKwh")
                        .HasColumnType("decimal(18,3)");

                    b.Property<decimal>("VariancePct")
                        .HasColumnType("decimal(9,2)");

                    b.HasKey("Id");

                    b.HasIndex("MeterId");

                    b.HasIndex("Status");

                    b.HasIndex("ConsumerId", "MeterId", "ValidationDate", "Rule")
                        .IsUnique();

                    b.ToTable("EnergyValidationResults", (string)null);
                });

            modelBuilder.Entity("PrepaidEngine.Domain.Entities.Feeder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("SubstationId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("SubstationId");

                    b.ToTable("Feeders", (string)null);
                });

            modelBuilder.Entity("PrepaidEngine.Domain.Entities.FppasCharge", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("NotifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("RateFraction")
                        .HasColumnType("decimal(9,4)");

                    b.Property<decimal>("SourceEnergyCharge")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("FppasCharges", (string)null);
                });

            modelBuilder.Entity("PrepaidEngine.Domain.Entities.InstantaneousReading", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ConsumerId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("CurrentAmps")
                        .HasColumnType("decimal(9,2)");

                    b.Property<decimal>("FrequencyHz")
                        .HasColumnType("decimal(5,2)");

                    b.Property<Guid>("MeterId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("PowerFactor")
                        .HasColumnType("decimal(4,3)");

                    b.Property<decimal>("PowerKw")
                        .HasColumnType("decimal(9,3)");

                    b.Property<DateTime>("ReceivedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RelayStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("SourceReference")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("VoltageVolts")
                        .HasColumnType("decimal(9,2)");

                    b.HasKey("Id");

                    b.HasIndex("ConsumerId");

                    b.HasIndex("MeterId", "Timestamp")
                        .IsUnique();

                    b.ToTable("InstantaneousReadings", (string)null);
                });

            modelBuilder.Entity("PrepaidEngine.Domain.Entities.LoadSurveyInterval", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ConsumerId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("ImportKwh")
                        .HasColumnType("decimal(18,3)");

                    b.Property<DateTime>("IntervalEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("IntervalStart")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("MeterId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ReceivedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SourceReference")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("IntervalStart");

                    b.HasIndex("MeterId");

                    b.HasIndex("ConsumerId", "MeterId", "IntervalStart")
                        .IsUnique();

                    b.ToTable("LoadSurveyIntervals", (string)null);
                });

            modelBuilder.Entity("PrepaidEngine.Domain.Entities.MeterAlarm", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("AcknowledgedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("AcknowledgedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("AlarmCode")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<Guid>("ConsumerId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("MeterId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("RaisedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ReceivedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ResolutionNote")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("SourceReference")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("ConsumerId");

                    b.HasIndex("RaisedAt");

                    b.HasIndex("Status");

                    b.HasIndex("MeterId", "AlarmCode", "RaisedAt")
                        .IsUnique();

                    b.ToTable("MeterAlarms", (string)null);
                });

            modelBuilder.Entity("PrepaidEngine.Domain.Entities.MeterAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ConsumerId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("EffectiveFrom")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("NewMeterId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("NewMeterOpeningReadingKwh")
                        .HasColumnType("decimal(18,3)");

                    b.Property<decimal?>("OldMeterClosingReadingKwh")
                        .HasColumnType("decimal(18,3)");

                    b.Property<Guid?>("OldMeterId")
                        .HasColumnType("uuid");

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("RecordedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ConsumerId");

                    b.ToTable("MeterAssignments", (string)null);
                });

            modelBuilder.Entity("PrepaidEngine.Domain.Entities.MeterBillingControl", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("ActualBillingBlocked")
                        .HasColumnType("boolean");

                    b.Property<string>("BlockReason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("BlockedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ClearedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ConsumerId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("MeterId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("MeterId");

                    b.HasIndex("ConsumerId", "MeterId")
                        .IsUnique();

                    b.ToTable("MeterBillingControls", (string)null);
                });

            modelBuilder.Entity("PrepaidEngine.Domain.Entities.MeterCommand", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("AcknowledgedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ConsumerId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("CreditAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("ExternalCommandId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("RechargeTransactionId")
                        .HasColumnType("uuid");

                    b.Property<string>("ResponseCode")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ResponseMessage")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("RetryCount")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("SentAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("Id");

                    b.HasIndex("ConsumerId");

                    b.HasIndex("RechargeTransactionId")
                        .IsUnique();

                    b.ToTable("MeterCommands", (string)null);
                });

            modelBuilder.Entity("PrepaidEngine.Domain.Entities.MeterEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ConsumerId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("EventCode")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<DateTime>("EventTimestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("MeterId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ReceivedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SourceReference")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("ConsumerId");

                    b.HasIndex("EventTimestamp");

                    b.HasIndex("MeterId", "EventCode", "EventTimestamp")
                        .IsUnique();

                    b.ToTable("MeterEvents", (string)null);
                });

            modelBuilder.Entity("PrepaidEngine.Domain.Entities.NotificationEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ConsumerId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("ProviderReference")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("SentAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("ConsumerId");

                    b.ToTable("NotificationEvents", (string)null);
                });

            modelBuilder.Entity("PrepaidEngine.Domain.Entities.OperationalException", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ConsumerId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("ResolutionNote")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("SourceId")
                        .HasColumnType("uuid");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("ConsumerId");

                    b.HasIndex("Status");

                    b.HasIndex("SourceType", "SourceId");

                    b.ToTable("OperationalExceptions", (string)null);
                });

            modelBuilder.Entity("PrepaidEngine.Domain.Entities.PaymentModeChangeCommand", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("AcknowledgedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ConsumerId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ConversionRequestId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<decimal?>("MeterReadingAtConversion")
                        .HasColumnType("decimal(18,3)");

                    b.Property<DateTime?>("SentAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("ConsumerId");

                    b.HasIndex("ConversionRequestId")
                        .IsUnique();

                    b.ToTable("PaymentModeChangeCommands", (string)null);
                });

            modelBuilder.Entity("PrepaidEngine.Domain.Entities.PrepaidBill", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("AmountPaid")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ArrearsAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ArrearsRecovered")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("ConsumerId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ConsumptionReadingId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("CpmcAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ElectricityDutyAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("EnergyChargeGross")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("FixedCharge")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("FppasAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid?>("FppasChargeId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("GeneratedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("PrepaidRebateAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<Guid>("TariffId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("TmcAmount")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ConsumerId");

                    b.HasIndex("ConsumptionReadingId")
                        .IsUnique();

                    b.HasIndex("FppasChargeId");

                    b.HasIndex("TariffId");

                    b.ToTable("PrepaidBills", (string)null);
                });

            modelBuilder.Entity("PrepaidEngine.Domain.Entities.PrepaidWallet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Balance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("ConsumerId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("EmergencyCreditLimit")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ConsumerId")
                        .IsUnique();

                    b.ToTable("PrepaidWallets", (string)null);
                });

            modelBuilder.Entity("PrepaidEngine.Domain.Entities.RechargeTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ConsumerId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("InitiatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RmsReferenceId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("Id");

                    b.HasIndex("ConsumerId");

                    b.HasIndex("RmsReferenceId")
                        .IsUnique();

                    b.ToTable("RechargeTransactions", (string)null);
                });

            modelBuilder.Entity("PrepaidEngine.Domain.Entities.ReconciliationAdjustment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("AppliedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("BalanceAfter")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("ConsumerId")
                        .HasColumnType("uuid");

                    b.Property<string>("ConsumerNumber")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("PaymentMode")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateTime>("ReconciliationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Reference")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("ConsumerId");

                    b.ToTable("ReconciliationAdjustments", (string)null);
                });

            modelBuilder.Entity("PrepaidEngine.Domain.Entities.RegisterReading", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ConsumerId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("CumulativeImportKwh")
                        .HasColumnType("decimal(18,3)");

                    b.Property<Guid>("MeterId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ReadingTimestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ReceivedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SourceReference")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("MeterId");

                    b.HasIndex("ReadingTimestamp");

                    b.HasIndex("ConsumerId", "MeterId", "ReadingTimestamp")
                        .IsUnique();

                    b.ToTable("RegisterReadings", (string)null);
                });

            modelBuilder.Entity("PrepaidEngine.Domain.Entities.ReverseConversionRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ConsumerId")
                        .HasColumnType("uuid");

                    b.Property<string>("DecisionNote")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<decimal?>("FinalMeterReadingKwh")
                        .HasColumnType("decimal(18,3)");

                    b.Property<decimal?>("FinalWalletBalance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("RequestedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RequestedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("ConsumerId");

                    b.ToTable("ReverseConversionRequests", (string)null);
                });

            modelBuilder.Entity("PrepaidEngine.Domain.Entities.SmartMeter", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("LastReadingAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("LastReadingKwh")
                        .HasColumnType("decimal(18,3)");

                    b.Property<string>("MeterNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Phase")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("MeterNumber")
                        .IsUnique();

                    b.ToTable("Meters", (string)null);
                });

            modelBuilder.Entity("PrepaidEngine.Domain.Entities.SubDivision", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<Guid>("DivisionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("DivisionId");

                    b.ToTable("SubDivisions", (string)null);
                });

            modelBuilder.Entity("PrepaidEngine.Domain.Entities.Substation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("SubDivisionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("SubDivisionId");

                    b.ToTable("Substations", (string)null);
                });

            modelBuilder.Entity("PrepaidEngine.Domain.Entities.Tariff", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<decimal>("EmergencyCreditLimit")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("FixedChargePerUnitPerMonth")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("MaxVendAmountSinglePhase")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("MaxVendAmountThreePhase")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("MinVendAmountSinglePhase")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("MinVendAmountThreePhase")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal>("PrepaidEnergyRebatePercent")
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Active");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasFilter("\"Status\" = 'Active'");

                    b.ToTable("Tariffs", (string)null);
                });

            modelBuilder.Entity("PrepaidEngine.Domain.Entities.TariffChangeRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ActivatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ApprovedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ChangeReason")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime?>("CommencementDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ProposedCategory")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<decimal>("ProposedEmergencyCreditLimit")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ProposedFixedChargePerUnitPerMonth")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("ProposedMaxVendAmountSinglePhase")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("ProposedMaxVendAmountThreePhase")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("ProposedMinVendAmountSinglePhase")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("ProposedMinVendAmountThreePhase")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ProposedName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal>("ProposedPrepaidEnergyRebatePercent")
                        .HasColumnType("decimal(5,2)");

                    b.Property<DateTime?>("RejectedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RejectedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("RejectionReason")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<Guid?>("ResultingTariffId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime?>("SubmittedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SubmittedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid?>("SupersedesTariffId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Status");

                    b.HasIndex("SupersedesTariffId");

                    b.ToTable("TariffChangeRequests", (string)null);
                });

            modelBuilder.Entity("PrepaidEngine.Domain.Entities.TariffVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ChangeNote")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime>("EffectiveDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FieldName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("NewValue")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("OldValue")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("RecordedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("TariffId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TariffId");

                    b.ToTable("TariffVersions", (string)null);
                });

            modelBuilder.Entity("PrepaidEngine.Domain.Entities.WalletTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Reference")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<Guid>("WalletId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("WalletId");

                    b.ToTable("WalletTransactions", (string)null);
                });

            modelBuilder.Entity("PrepaidEngine.Domain.Entities.Zone", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Zones", (string)null);
                });

            modelBuilder.Entity("PrepaidEngine.Domain.Entities.Circle", b =>
                {
                    b.HasOne("PrepaidEngine.Domain.Entities.Zone", "Zone")
                        .WithMany()
                        .HasForeignKey("ZoneId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Zone");
                });

            modelBuilder.Entity("PrepaidEngine.Domain.Entities.ConnectivityCommand", b =>
                {
                    b.HasOne("PrepaidEngine.Domain.Entities.Consumer", null)
                        .WithMany()
                        .HasForeignKey("ConsumerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("PrepaidEngine.Domain.Entities.Consumer", b =>
                {
                    b.HasOne("PrepaidEngine.Domain.Entities.Dtr", "Dtr")
                        .WithMany()
                        .HasForeignKey("DtrId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PrepaidEngine.Domain.Entities.SmartMeter", "Meter")
                        .WithOne()
                        .HasForeignKey("PrepaidEngine.Domain.Entities.Consumer", "MeterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Dtr");

                    b.Navigation("Meter");
                });

            modelBuilder.Entity("PrepaidEngine.Domain.Entities.ConsumptionReading", b =>
                {
                    b.HasOne("PrepaidEngine.Domain.Entities.Consumer", null)
                        .WithMany()
                        .HasForeignKey("ConsumerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("PrepaidEngine.Domain.Entities.ConversionRequest", b =>
                {
                    b.HasOne("PrepaidEngine.Domain.Entities.Consumer", null)
                        .WithMany()
                        .HasForeignKey("ConsumerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("PrepaidEngine.Domain.Entities.DailyLoadProfile", b =>
                {
                    b.HasOne("PrepaidEngine.Domain.Entities.Consumer", null)
                        .WithMany()
                        .HasForeignKey("ConsumerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PrepaidEngine.Domain.Entities.SmartMeter", null)
                        .WithMany()
                        .HasForeignKey("MeterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("PrepaidEngine.Domain.Entities.Division", b =>
                {
                    b.HasOne("PrepaidEngine.Domain.Entities.Circle", "Circle")
                        .WithMany()
                        .HasForeignKey("CircleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Circle");
                });

            modelBuilder.Entity("PrepaidEngine.Domain.Entities.Dtr", b =>
                {
                    b.HasOne("PrepaidEngine.Domain.Entities.Feeder", "Feeder")
                        .WithMany()
                        .HasForeignKey("FeederId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Feeder");
                });

            modelBuilder.Entity("PrepaidEngine.Domain.Entities.EnergyValidationResult", b =>
                {
                    b.HasOne("PrepaidEngine.Domain.Entities.Consumer", null)
                        .WithMany()
                        .HasForeignKey("ConsumerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PrepaidEngine.Domain.Entities.SmartMeter", null)
                        .WithMany()
                        .HasForeignKey("MeterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("PrepaidEngine.Domain.Entities.Feeder", b =>
                {
                    b.HasOne("PrepaidEngine.Domain.Entities.Substation", "Substation")
                        .WithMany()
                        .HasForeignKey("SubstationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Substation");
                });

            modelBuilder.Entity("PrepaidEngine.Domain.Entities.InstantaneousReading", b =>
                {
                    b.HasOne("PrepaidEngine.Domain.Entities.Consumer", null)
                        .WithMany()
                        .HasForeignKey("ConsumerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PrepaidEngine.Domain.Entities.SmartMeter", null)
                        .WithMany()
                        .HasForeignKey("MeterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("PrepaidEngine.Domain.Entities.LoadSurveyInterval", b =>
                {
                    b.HasOne("PrepaidEngine.Domain.Entities.Consumer", null)
                        .WithMany()
                        .HasForeignKey("ConsumerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PrepaidEngine.Domain.Entities.SmartMeter", null)
                        .WithMany()
                        .HasForeignKey("MeterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("PrepaidEngine.Domain.Entities.MeterAlarm", b =>
                {
                    b.HasOne("PrepaidEngine.Domain.Entities.Consumer", null)
                        .WithMany()
                        .HasForeignKey("ConsumerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PrepaidEngine.Domain.Entities.SmartMeter", null)
                        .WithMany()
                        .HasForeignKey("MeterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("PrepaidEngine.Domain.Entities.MeterAssignment", b =>
                {
                    b.HasOne("PrepaidEngine.Domain.Entities.Consumer", null)
                        .WithMany()
                        .HasForeignKey("ConsumerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("PrepaidEngine.Domain.Entities.MeterBillingControl", b =>
                {
                    b.HasOne("PrepaidEngine.Domain.Entities.Consumer", null)
                        .WithMany()
                        .HasForeignKey("ConsumerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PrepaidEngine.Domain.Entities.SmartMeter", null)
                        .WithMany()
                        .HasForeignKey("MeterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("PrepaidEngine.Domain.Entities.MeterCommand", b =>
                {
                    b.HasOne("PrepaidEngine.Domain.Entities.Consumer", null)
                        .WithMany()
                        .HasForeignKey("ConsumerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PrepaidEngine.Domain.Entities.RechargeTransaction", null)
                        .WithMany()
                        .HasForeignKey("RechargeTransactionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("PrepaidEngine.Domain.Entities.MeterEvent", b =>
                {
                    b.HasOne("PrepaidEngine.Domain.Entities.Consumer", null)
                        .WithMany()
                        .HasForeignKey("ConsumerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PrepaidEngine.Domain.Entities.SmartMeter", null)
                        .WithMany()
                        .HasForeignKey("MeterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("PrepaidEngine.Domain.Entities.NotificationEvent", b =>
                {
                    b.HasOne("PrepaidEngine.Domain.Entities.Consumer", null)
                        .WithMany()
                        .HasForeignKey("ConsumerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("PrepaidEngine.Domain.Entities.OperationalException", b =>
                {
                    b.HasOne("PrepaidEngine.Domain.Entities.Consumer", null)
                        .WithMany()
                        .HasForeignKey("ConsumerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("PrepaidEngine.Domain.Entities.PaymentModeChangeCommand", b =>
                {
                    b.HasOne("PrepaidEngine.Domain.Entities.Consumer", null)
                        .WithMany()
                        .HasForeignKey("ConsumerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PrepaidEngine.Domain.Entities.ConversionRequest", null)
                        .WithMany()
                        .HasForeignKey("ConversionRequestId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("PrepaidEngine.Domain.Entities.PrepaidBill", b =>
                {
                    b.HasOne("PrepaidEngine.Domain.Entities.Consumer", null)
                        .WithMany()
                        .HasForeignKey("ConsumerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PrepaidEngine.Domain.Entities.ConsumptionReading", null)
                        .WithMany()
                        .HasForeignKey("ConsumptionReadingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PrepaidEngine.Domain.Entities.FppasCharge", null)
                        .WithMany()
                        .HasForeignKey("FppasChargeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PrepaidEngine.Domain.Entities.Tariff", null)
                        .WithMany()
                        .HasForeignKey("TariffId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("PrepaidEngine.Domain.Entities.PrepaidWallet", b =>
                {
                    b.HasOne("PrepaidEngine.Domain.Entities.Consumer", null)
                        .WithOne("Wallet")
                        .HasForeignKey("PrepaidEngine.Domain.Entities.PrepaidWallet", "ConsumerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PrepaidEngine.Domain.Entities.RechargeTransaction", b =>
                {
                    b.HasOne("PrepaidEngine.Domain.Entities.Consumer", null)
                        .WithMany()
                        .HasForeignKey("ConsumerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("PrepaidEngine.Domain.Entities.ReconciliationAdjustment", b =>
                {
                    b.HasOne("PrepaidEngine.Domain.Entities.Consumer", null)
                        .WithMany()
                        .HasForeignKey("ConsumerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("PrepaidEngine.Domain.Entities.RegisterReading", b =>
                {
                    b.HasOne("PrepaidEngine.Domain.Entities.Consumer", null)
                        .WithMany()
                        .HasForeignKey("ConsumerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PrepaidEngine.Domain.Entities.SmartMeter", null)
                        .WithMany()
                        .HasForeignKey("MeterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("PrepaidEngine.Domain.Entities.ReverseConversionRequest", b =>
                {
                    b.HasOne("PrepaidEngine.Domain.Entities.Consumer", null)
                        .WithMany()
                        .HasForeignKey("ConsumerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("PrepaidEngine.Domain.Entities.SubDivision", b =>
                {
                    b.HasOne("PrepaidEngine.Domain.Entities.Division", "Division")
                        .WithMany()
                        .HasForeignKey("DivisionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Division");
                });

            modelBuilder.Entity("PrepaidEngine.Domain.Entities.Substation", b =>
                {
                    b.HasOne("PrepaidEngine.Domain.Entities.SubDivision", "SubDivision")
                        .WithMany()
                        .HasForeignKey("SubDivisionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("SubDivision");
                });

            modelBuilder.Entity("PrepaidEngine.Domain.Entities.Tariff", b =>
                {
                    b.OwnsMany("PrepaidEngine.Domain.Entities.TariffSlab", "Slabs", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid");

                            b1.Property<decimal>("FromKwh")
                                .HasColumnType("decimal(18,3)");

                            b1.Property<decimal>("RatePerKwh")
                                .HasColumnType("decimal(18,4)");

                            b1.Property<Guid>("TariffId")
                                .HasColumnType("uuid");

                            b1.Property<decimal?>("UpToKwh")
                                .HasColumnType("decimal(18,3)");

                            b1.HasKey("Id");

                            b1.HasIndex("TariffId");

                            b1.ToTable("TariffSlabs", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("TariffId");
                        });

                    b.OwnsMany("PrepaidEngine.Domain.Entities.TouPeriod", "TouPeriods", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid");

                            b1.Property<TimeSpan>("EndTime")
                                .HasColumnType("interval");

                            b1.Property<string>("Label")
                                .IsRequired()
                                .HasMaxLength(30)
                                .HasColumnType("character varying(30)");

                            b1.Property<decimal>("RatePerKvah")
                                .HasColumnType("decimal(18,4)");

                            b1.Property<TimeSpan>("StartTime")
                                .HasColumnType("interval");

                            b1.Property<Guid>("TariffId")
                                .HasColumnType("uuid");

                            b1.HasKey("Id");

                            b1.HasIndex("TariffId");

                            b1.ToTable("TouPeriods", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("TariffId");
                        });

                    b.Navigation("Slabs");

                    b.Navigation("TouPeriods");
                });

            modelBuilder.Entity("PrepaidEngine.Domain.Entities.TariffChangeRequest", b =>
                {
                    b.OwnsMany("PrepaidEngine.Domain.Entities.TariffSlab", "ProposedSlabs", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid");

                            b1.Property<decimal>("FromKwh")
                                .HasColumnType("decimal(18,3)");

                            b1.Property<decimal>("RatePerKwh")
                                .HasColumnType("decimal(18,4)");

                            b1.Property<Guid>("TariffChangeRequestId")
                                .HasColumnType("uuid");

                            b1.Property<decimal?>("UpToKwh")
                                .HasColumnType("decimal(18,3)");

                            b1.HasKey("Id");

                            b1.HasIndex("TariffChangeRequestId");

                            b1.ToTable("TariffChangeRequestSlabs", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("TariffChangeRequestId");
                        });

                    b.OwnsMany("PrepaidEngine.Domain.Entities.TouPeriod", "ProposedTouPeriods", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid");

                            b1.Property<TimeSpan>("EndTime")
                                .HasColumnType("interval");

                            b1.Property<string>("Label")
                                .IsRequired()
                                .HasMaxLength(30)
                                .HasColumnType("character varying(30)");

                            b1.Property<decimal>("RatePerKvah")
                                .HasColumnType("decimal(18,4)");

                            b1.Property<TimeSpan>("StartTime")
                                .HasColumnType("interval");

                            b1.Property<Guid>("TariffChangeRequestId")
                                .HasColumnType("uuid");

                            b1.HasKey("Id");

                            b1.HasIndex("TariffChangeRequestId");

                            b1.ToTable("TariffChangeRequestTouPeriods", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("TariffChangeRequestId");
                        });

                    b.Navigation("ProposedSlabs");

                    b.Navigation("ProposedTouPeriods");
                });

            modelBuilder.Entity("PrepaidEngine.Domain.Entities.TariffVersion", b =>
                {
                    b.HasOne("PrepaidEngine.Domain.Entities.Tariff", null)
                        .WithMany()
                        .HasForeignKey("TariffId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("PrepaidEngine.Domain.Entities.WalletTransaction", b =>
                {
                    b.HasOne("PrepaidEngine.Domain.Entities.PrepaidWallet", null)
                        .WithMany("Transactions")
                        .HasForeignKey("WalletId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PrepaidEngine.Domain.Entities.Consumer", b =>
                {
                    b.Navigation("Wallet")
                        .IsRequired();
                });

            modelBuilder.Entity("PrepaidEngine.Domain.Entities.PrepaidWallet", b =>
                {
                    b.Navigation("Transactions");
                });
#pragma warning restore 612, 618
        }
    }
}
